const express = require("express");
const router = express.Router();
//import * as authController from "../controllers/auth.controller";
import * as postController from "../controllers/post.controller";
// router.post("/register", authController.register);
// router.post("/login", authController.login);
router.post("/create-post", postController.createPost);
router.put("/update-company/:id", postController.updatePost);
router.get("/get-post/:id", postController.getPostById);
router.get("/all", postController.getAllPosts);
router.get("/limit", postController.getLimitPosts);
module.exports = router;
